version: "3.7"

services:

  api_mini_meli:
    container_name: api_mini_meli
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  client_mini_meli:
    container_name: client_mini_meli
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


